// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxyzmxqtzsvjezmkmkja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54eXpteHF0enN2amV6bWtta2phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMTA0MDMsImV4cCI6MjA2ODg4NjQwM30.PlQCqVJcpDCVojXZ2VaaLiGTQUETaC9cVQe_owgjJ60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});